# Generated by ChatGPT (custom project scaffold)
from django.db import migrations, models
import django.db.models.deletion
import arena.models

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("CONFIGURED", "Configured"), ("RUNNING", "Running"), ("PAUSED", "Paused"), ("FINISHED", "Finished")], default="CONFIGURED", max_length=16)),
                ("fen", models.TextField(default=arena.models.STARTPOS_FEN)),
                ("side_to_move", models.CharField(default="w", max_length=5)),
                ("ply_count", models.PositiveIntegerField(default=0)),
                ("move_interval_ms", models.PositiveIntegerField(default=500)),
                ("next_action_at", models.DateTimeField(blank=True, null=True)),
                ("last_move_uci", models.CharField(blank=True, default="", max_length=8)),
                ("last_move_san", models.CharField(blank=True, default="", max_length=16)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.CharField(blank=True, default="", max_length=7)),
                ("termination_reason", models.CharField(blank=True, choices=[("CHECKMATE", "Checkmate"), ("STALEMATE", "Stalemate"), ("REPETITION", "Threefold repetition"), ("FIFTY_MOVE", "Fifty-move rule"), ("INSUFFICIENT", "Insufficient material"), ("RESIGN", "Forfeit / engine error"), ("MAX_PLIES", "Max plies reached"), ("UNKNOWN", "Unknown")], default="", max_length=16)),
                ("initial_position_key", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EngineConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("side", models.CharField(choices=[("WHITE", "White"), ("BLACK", "Black")], max_length=5)),
                ("engine_type", models.CharField(default="STOCKFISH", max_length=16)),
                ("strength_mode", models.CharField(choices=[("SKILL", "Skill (1-20)"), ("ELO", "Elo (UCI_Elo)")], default="SKILL", max_length=8)),
                ("strength_value", models.PositiveIntegerField(default=10)),
                ("movetime_ms", models.PositiveIntegerField(default=150)),
                ("uci_options", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="engines", to="arena.game")),
            ],
            options={"unique_together": {("game", "side")}},
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ply_index", models.PositiveIntegerField()),
                ("uci", models.CharField(max_length=8)),
                ("san", models.CharField(blank=True, default="", max_length=16)),
                ("fen_after", models.TextField()),
                ("position_key_after", models.CharField(blank=True, default="", max_length=64)),
                ("is_check", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="moves", to="arena.game")),
            ],
            options={"ordering": ["ply_index"], "unique_together": {("game", "ply_index")}},
        ),
        migrations.CreateModel(
            name="MatchRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("result", models.CharField(max_length=7)),
                ("termination_reason", models.CharField(max_length=16)),
                ("white_strength_mode", models.CharField(max_length=8)),
                ("white_strength_value", models.PositiveIntegerField()),
                ("black_strength_mode", models.CharField(max_length=8)),
                ("black_strength_value", models.PositiveIntegerField()),
                ("move_interval_ms", models.PositiveIntegerField()),
                ("pgn", models.TextField(blank=True, default="")),
                ("finished_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="match_record", to="arena.game")),
            ],
        ),
    ]
