# Generated by Django 6.0 on 2026-01-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_add_pending_move_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineconfig',
            name='engine_type',
            field=models.CharField(choices=[('STOCKFISH', 'Stockfish (UCI)'), ('PYCHESS', 'PyChess (python-chess minimax)')], default='STOCKFISH', max_length=16),
        ),
    ]
