# Generated by Django 6.0 on 2026-01-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_add_game_preview_ms'),
        ('arena', '0003_alter_engineconfig_engine_type'),
    ]

    operations = [
    ]
