# Generated by Django 6.0 on 2026-01-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_add_player_ui_selection'),
        ('arena', '0004_merge_20260106_1950'),
    ]

    operations = [
    ]
