# Generated by Django 6.0 on 2026-01-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_add_game_tick_lock'),
        ('arena', '0005_merge_20260107_1326'),
    ]

    operations = [
    ]
